apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: y19vb3sxs-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: y19vb3sxs-go 
  name: y19vb3sxs-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: y19vb3sxs-go 
